Repository UMC-Plantory/Spring, pull requests merged in 2025-07, with the labels that each got.

#2 [#1] API 응답 통일 코드 추가
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/umc/plantory/PlantoryApplication.java
  src/main/java/umc/plantory/apiPayload/ApiResponse.java
  src/main/java/umc/plantory/apiPayload/code/BaseCode.java
  src/main/java/umc/plantory/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/plantory/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/plantory/apiPayload/code/ReasonDTO.java
  src/main/java/umc/plantory/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/plantory/apiPayload/code/status/SuccessStatus.java
  src/test/java/umc/plantory/PlantoryApplicationTests.java
Labels: ⚙️ CHORE

#4 [#1] API 응답 코드 추가
  .github/ISSUE_TEMPLATE/✨-기능.md
  .github/ISSUE_TEMPLATE/🐞-버그.md
  .github/ISSUE_TEMPLATE/📚-기본-이슈-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  src/main/java/umc/plantory/apiPayload/ApiResponse.java
  src/main/java/umc/plantory/apiPayload/code/BaseCode.java
  src/main/java/umc/plantory/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/plantory/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/plantory/apiPayload/code/ReasonDTO.java
  src/main/java/umc/plantory/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/plantory/apiPayload/code/status/SuccessStatus.java
Labels: ⚙️ CHORE

#7 [#6] 스웨거 설정 코드 추가
  build.gradle
  src/main/java/umc/plantory/config/SwaggerConfig.java
Labels: ⚙️ CHORE

#15 [Chore] Chat entity 길이 제한 어노테이션 추가
  src/main/java/umc/plantory/domain/chat/entity/Chat.java
Labels: ⚙️ CHORE

#18 [#16] 챗봇 API 기능 구현
  build.gradle
  src/main/java/umc/plantory/domain/chat/controller/ChatCommandApi.java
  src/main/java/umc/plantory/domain/chat/controller/ChatCommandController.java
  src/main/java/umc/plantory/domain/chat/controller/ChatQueryApi.java
  src/main/java/umc/plantory/domain/chat/controller/ChatQueryController.java
  src/main/java/umc/plantory/domain/chat/controller/dto/ChatRequestDto.java
  src/main/java/umc/plantory/domain/chat/controller/dto/ChatResponseDto.java
  src/main/java/umc/plantory/domain/chat/converter/ChatConverter.java
  src/main/java/umc/plantory/domain/chat/entity/Chat.java
  src/main/java/umc/plantory/domain/chat/exception/ChatApiException.java
  src/main/java/umc/plantory/domain/chat/prompt/PromptFactory.java
  src/main/java/umc/plantory/domain/chat/repository/ChatJpaRepository.java
  src/main/java/umc/plantory/domain/chat/service/ChatCommandService.java
  src/main/java/umc/plantory/domain/chat/service/ChatCommandUseCase.java
  src/main/java/umc/plantory/domain/chat/service/ChatQueryService.java
  src/main/java/umc/plantory/domain/chat/service/ChatQueryUseCase.java
  src/main/java/umc/plantory/domain/member/repository/MemberRepository.java
  src/main/java/umc/plantory/domain/wateringCan/entity/WateringCan.java
  src/main/java/umc/plantory/domain/wateringCan/entity/WateringEvent.java
  src/main/java/umc/plantory/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/plantory/global/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/plantory/global/config/SwaggerConfig.java
Labels: :sparkles: FEAT

#19 [#13] 일기 작성 API 구현
  build.gradle
  src/main/java/umc/plantory/domain/diary/controller/DiaryRestController.java
  src/main/java/umc/plantory/domain/diary/converter/DiaryConverter.java
  src/main/java/umc/plantory/domain/diary/dto/request/DiaryRequestDTO.java
  src/main/java/umc/plantory/domain/diary/dto/response/DiaryResponseDTO.java
  src/main/java/umc/plantory/domain/diary/repository/DiaryImgRepository.java
  src/main/java/umc/plantory/domain/diary/repository/DiaryRepository.java
  src/main/java/umc/plantory/domain/diary/service/DiaryCommandService.java
  src/main/java/umc/plantory/domain/diary/service/DiaryCommandUseCase.java
  src/main/java/umc/plantory/domain/image/controller/ImageRestController.java
  src/main/java/umc/plantory/domain/image/converter/ImageConverter.java
  src/main/java/umc/plantory/domain/image/dto/request/PresignedUrlRequestDTO.java
  src/main/java/umc/plantory/domain/image/dto/response/PresignedUrlResponseDTO.java
  src/main/java/umc/plantory/domain/image/service/ImageService.java
  src/main/java/umc/plantory/domain/image/service/ImageUseCase.java
  src/main/java/umc/plantory/domain/member/entity/Member.java
  src/main/java/umc/plantory/domain/wateringCan/converter/WateringCanConverter.java
  src/main/java/umc/plantory/domain/wateringCan/entity/WateringCan.java
  src/main/java/umc/plantory/domain/wateringCan/repository/WateringCanRepository.java
  src/main/java/umc/plantory/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/plantory/global/apiPayload/exception/handler/ImageHandler.java
  src/main/java/umc/plantory/global/apiPayload/exception/handler/MemberHandler.java
  src/main/java/umc/plantory/global/config/AmazonConfig.java
  src/main/java/umc/plantory/global/validation/annotation/ValidDiaryFields.java
  src/main/java/umc/plantory/global/validation/validator/DiaryFieldsValidator.java
Labels: :sparkles: FEAT

#30 [#29] Kakao 소셜 로그인 구현
  build.gradle
  src/main/java/umc/plantory/domain/kakao/converter/KakaoConverter.java
  src/main/java/umc/plantory/domain/kakao/service/KakaoOidcService.java
  src/main/java/umc/plantory/domain/member/controller/MemberRestController.java
  src/main/java/umc/plantory/domain/member/converter/MemberConverter.java
  src/main/java/umc/plantory/domain/member/dto/MemberDataDTO.java
  src/main/java/umc/plantory/domain/member/dto/MemberRequestDTO.java
  src/main/java/umc/plantory/domain/member/dto/MemberResponseDTO.java
  src/main/java/umc/plantory/domain/member/entity/Member.java
  src/main/java/umc/plantory/domain/member/repository/MemberRepository.java
  src/main/java/umc/plantory/domain/member/service/MemberCommandService.java
  src/main/java/umc/plantory/domain/member/service/MemberCommandUseCase.java
  src/main/java/umc/plantory/domain/token/converter/MemberTokenConverter.java
  src/main/java/umc/plantory/domain/token/entity/MemberToken.java
  src/main/java/umc/plantory/domain/token/provider/JwtProvider.java
  src/main/java/umc/plantory/domain/token/repository/MemberTokenRepository.java
  src/main/java/umc/plantory/domain/token/service/MemberTokenCommandService.java
  src/main/java/umc/plantory/domain/token/service/MemberTokenCommandUseCase.java
  src/main/java/umc/plantory/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/plantory/global/apiPayload/exception/handler/JwtHandler.java
  src/main/java/umc/plantory/global/apiPayload/exception/handler/KakaoHandler.java
  src/main/java/umc/plantory/global/config/SwaggerConfig.java
  src/main/java/umc/plantory/global/enums/Gender.java
Labels: :sparkles: FEAT

#31 [#28] 유저 마이페이지 조회 API 구현
  src/main/java/umc/plantory/domain/member/controller/MemberRestController.java
  src/main/java/umc/plantory/domain/member/converter/MemberConverter.java
  src/main/java/umc/plantory/domain/member/dto/MemberResponseDTO.java
  src/main/java/umc/plantory/domain/member/entity/Member.java
  src/main/java/umc/plantory/domain/member/repository/MemberRepository.java
  src/main/java/umc/plantory/domain/member/service/MemberCommandService.java
  src/main/java/umc/plantory/domain/member/service/MemberCommandUseCase.java
  src/main/java/umc/plantory/domain/member/service/MemberQueryService.java
  src/main/java/umc/plantory/domain/member/service/MemberQueryUseCase.java
  src/main/java/umc/plantory/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/plantory/global/apiPayload/exception/handler/TermHandler.java
Labels: :sparkles: FEAT

#32 [#22] 일기 업데이트 관련 API 개발
  src/main/java/umc/plantory/domain/diary/controller/DiaryRestController.java
  src/main/java/umc/plantory/domain/diary/converter/DiaryConverter.java
  src/main/java/umc/plantory/domain/diary/dto/DiaryRequestDTO.java
  src/main/java/umc/plantory/domain/diary/dto/DiaryResponseDTO.java
  src/main/java/umc/plantory/domain/diary/entity/Diary.java
  src/main/java/umc/plantory/domain/diary/entity/DiaryImg.java
  src/main/java/umc/plantory/domain/diary/repository/DiaryImgRepository.java
  src/main/java/umc/plantory/domain/diary/service/DiaryCommandService.java
  src/main/java/umc/plantory/domain/diary/service/DiaryCommandUseCase.java
  src/main/java/umc/plantory/domain/image/controller/ImageRestController.java
  src/main/java/umc/plantory/domain/image/converter/ImageConverter.java
  src/main/java/umc/plantory/domain/image/dto/PresignedUrlRequestDTO.java
  src/main/java/umc/plantory/domain/image/dto/PresignedUrlResponseDTO.java
  src/main/java/umc/plantory/domain/image/service/ImageService.java
  src/main/java/umc/plantory/domain/image/service/ImageUseCase.java
  src/main/java/umc/plantory/domain/wateringCan/converter/WateringCanConverter.java
  src/main/java/umc/plantory/domain/wateringCan/entity/WateringCan.java
  src/main/java/umc/plantory/domain/wateringCan/repository/WateringCanRepository.java
  src/main/java/umc/plantory/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/plantory/global/apiPayload/exception/handler/DiaryHandler.java
  src/main/java/umc/plantory/global/validation/validator/DiaryFieldsValidator.java
Labels: :sparkles: FEAT

#44 [#43] RequestHeader 에 required = false 추가
  src/main/java/umc/plantory/domain/diary/controller/DiaryRestController.java
  src/main/java/umc/plantory/domain/member/controller/MemberRestController.java
Labels: :recycle: REFACTOR
