Repository UMC-Plantory/Spring, pull requests merged in 2025-08, with the labels that each got.

#34 [#21] 유저 로그아웃 & 계정탈퇴 API 구현
  src/main/java/umc/plantory/domain/member/controller/MemberRestController.java
  src/main/java/umc/plantory/domain/member/converter/MemberConverter.java
  src/main/java/umc/plantory/domain/member/dto/MemberResponseDTO.java
  src/main/java/umc/plantory/domain/member/entity/Member.java
  src/main/java/umc/plantory/domain/member/service/MemberCommandService.java
  src/main/java/umc/plantory/domain/member/service/MemberCommandUseCase.java
  src/main/java/umc/plantory/domain/token/repository/MemberTokenRepository.java
Labels: :sparkles: FEAT

#37 [#35] 유저 프로필 수정 API 구현
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/umc/.DS_Store
  src/main/java/umc/plantory/.DS_Store
  src/main/java/umc/plantory/domain/member/controller/MemberRestController.java
  src/main/java/umc/plantory/domain/member/converter/MemberConverter.java
  src/main/java/umc/plantory/domain/member/dto/MemberRequestDTO.java
  src/main/java/umc/plantory/domain/member/dto/MemberResponseDTO.java
  src/main/java/umc/plantory/domain/member/service/MemberCommandService.java
  src/main/java/umc/plantory/domain/member/service/MemberCommandUseCase.java
  src/main/java/umc/plantory/domain/member/service/MemberQueryUseCase.java
Labels: :sparkles: FEAT

#38 [#17] 통계 API 구현
  src/main/java/umc/plantory/domain/diary/entity/Diary.java
  src/main/java/umc/plantory/domain/diary/repository/DiaryRepository.java
  src/main/java/umc/plantory/domain/statistic/controller/StatisticRestController.java
  src/main/java/umc/plantory/domain/statistic/converter/StatisticConverter.java
  src/main/java/umc/plantory/domain/statistic/dto/response/StatisticResponseDTO.java
  src/main/java/umc/plantory/domain/statistic/service/StatisticQueryService.java
  src/main/java/umc/plantory/domain/statistic/service/StatisticQueryUseCase.java
  src/main/java/umc/plantory/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/plantory/global/apiPayload/exception/handler/StatisticHandler.java
  src/main/java/umc/plantory/global/enums/Emotion.java
Labels: :sparkles: FEAT

#41 [#40] 액세스 토큰 재발급 API 구현
  src/main/java/umc/plantory/domain/member/dto/MemberRequestDTO.java
  src/main/java/umc/plantory/domain/member/dto/MemberResponseDTO.java
  src/main/java/umc/plantory/domain/token/controller/MemberTokenRestController.java
  src/main/java/umc/plantory/domain/token/converter/MemberTokenConverter.java
  src/main/java/umc/plantory/domain/token/repository/MemberTokenRepository.java
  src/main/java/umc/plantory/domain/token/service/MemberTokenCommandService.java
  src/main/java/umc/plantory/domain/token/service/MemberTokenCommandUseCase.java
  src/main/java/umc/plantory/global/apiPayload/code/status/ErrorStatus.java
Labels: :sparkles: FEAT

#45 [#33] 일기 단건 조회 API 개발
  src/main/java/umc/plantory/domain/diary/controller/DiaryCommandController.java
  src/main/java/umc/plantory/domain/diary/controller/DiaryQueryController.java
  src/main/java/umc/plantory/domain/diary/converter/DiaryConverter.java
  src/main/java/umc/plantory/domain/diary/dto/DiaryResponseDTO.java
  src/main/java/umc/plantory/domain/diary/repository/DiaryRepository.java
  src/main/java/umc/plantory/domain/diary/service/DiaryQueryService.java
  src/main/java/umc/plantory/domain/diary/service/DiaryQueryUseCase.java
Labels: :sparkles: FEAT

#48 [Refactor] Entity 필드명 수정 및 조건 수정
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/umc/.DS_Store
  src/main/java/umc/plantory/.DS_Store
  src/main/java/umc/plantory/domain/kakao/converter/KakaoConverter.java
  src/main/java/umc/plantory/domain/member/dto/MemberResponseDTO.java
  src/main/java/umc/plantory/domain/member/entity/Member.java
  src/main/java/umc/plantory/domain/member/service/MemberCommandService.java
  src/main/java/umc/plantory/domain/token/converter/MemberTokenConverter.java
  src/main/java/umc/plantory/domain/token/entity/MemberToken.java
  src/main/java/umc/plantory/domain/token/service/MemberTokenCommandService.java
  src/main/java/umc/plantory/global/apiPayload/code/status/ErrorStatus.java
Labels: :recycle: REFACTOR

#53 [#50] CI/CD 파이프라인 구축 테스트
  .github/workflows/dev_deploy.yml
Labels: :truck: CI/CD

#54 [CI/CD] CI/CD 파이프라인 구축
  .github/workflows/dev_deploy.yml
Labels: :truck: CI/CD

#56 [#50] CI/CD 파이프라인 구축
  .github/workflows/dev_deploy.yml
Labels: :truck: CI/CD

#57 [#50] CI/CD 파이프라인 구축
  .github/workflows/dev_deploy.yml
Labels: :truck: CI/CD

#58 [#50] CI/CD 파이프라인 구축
  .github/workflows/dev_deploy.yml
  Dockerfile
Labels: :truck: CI/CD

#60 [#50] CI/CD 파이프라인 구축
  .github/workflows/dev_deploy.yml
Labels: :truck: CI/CD

#68 [#12] 테라리움 API 개발
  gradlew
  src/main/java/umc/plantory/domain/flower/repository/FlowerRepository.java
  src/main/java/umc/plantory/domain/member/entity/Member.java
  src/main/java/umc/plantory/domain/member/repository/MemberRepository.java
  src/main/java/umc/plantory/domain/member/service/MemberCommandService.java
  src/main/java/umc/plantory/domain/terrarium/controller/TerrariumRestController.java
  src/main/java/umc/plantory/domain/terrarium/converter/TerrariumConverter.java
  src/main/java/umc/plantory/domain/terrarium/dto/TerrariumResponseDto.java
  src/main/java/umc/plantory/domain/terrarium/entity/Terrarium.java
  src/main/java/umc/plantory/domain/terrarium/repository/TerrariumRepository.java
  src/main/java/umc/plantory/domain/terrarium/service/TerrariumCommandService.java
  src/main/java/umc/plantory/domain/terrarium/service/TerrariumCommandUseCase.java
  src/main/java/umc/plantory/domain/terrarium/service/TerrariumQueryService.java
  src/main/java/umc/plantory/domain/terrarium/service/TerrariumQueryUseCase.java
  src/main/java/umc/plantory/domain/wateringCan/converter/WateringEventConverter.java
  src/main/java/umc/plantory/domain/wateringCan/repository/WateringCanRepository.java
  src/main/java/umc/plantory/domain/wateringCan/repository/WateringEventRepository.java
  src/main/java/umc/plantory/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/plantory/global/apiPayload/exception/handler/FlowerHandler.java
  src/main/java/umc/plantory/global/apiPayload/exception/handler/TerrariumHandler.java
  src/main/java/umc/plantory/global/enums/Emotion.java
Labels: :sparkles: FEAT

#72 [#63] 일기 검색 API 개발
  src/main/java/umc/plantory/domain/diary/controller/DiaryQueryController.java
  src/main/java/umc/plantory/domain/diary/controller/DiaryRestController.java
  src/main/java/umc/plantory/domain/diary/converter/DiaryConverter.java
  src/main/java/umc/plantory/domain/diary/dto/DiaryResponseDTO.java
  src/main/java/umc/plantory/domain/diary/repository/DiaryRepositoryCustom.java
  src/main/java/umc/plantory/domain/diary/repository/DiaryRepositoryImpl.java
  src/main/java/umc/plantory/domain/diary/service/DiaryQueryService.java
  src/main/java/umc/plantory/domain/diary/service/DiaryQueryUseCase.java
Labels: :sparkles: FEAT

#71 [#29] 프로젝트 Spring Security 적용 + 토큰에서 memberId 추출 간소화
  build.gradle
  src/main/java/umc/plantory/domain/kakao/converter/KakaoConverter.java
  src/main/java/umc/plantory/domain/kakao/service/KakaoOidcService.java
  src/main/java/umc/plantory/domain/token/filter/JwtAuthenticationFilter.java
  src/main/java/umc/plantory/domain/token/provider/JwtProvider.java
  src/main/java/umc/plantory/global/enums/MemberRole.java
  src/main/java/umc/plantory/global/security/CustomUserDetails.java
  src/main/java/umc/plantory/global/security/CustomUserDetailsService.java
  src/main/java/umc/plantory/global/security/config/SecurityConfig.java
Labels: :recycle: REFACTOR

#80 [#66] 임시 보관, 휴지통에서 30일 지난 일기 처리 구현
  src/main/java/umc/plantory/PlantoryApplication.java
  src/main/java/umc/plantory/domain/diary/entity/Diary.java
  src/main/java/umc/plantory/domain/diary/repository/DiaryImgRepository.java
  src/main/java/umc/plantory/domain/diary/repository/DiaryRepository.java
  src/main/java/umc/plantory/domain/diary/scheduler/DiaryScheduler.java
  src/main/java/umc/plantory/domain/diary/scheduler/DiarySchedulerJob.java
  src/main/java/umc/plantory/domain/diary/service/DiaryCommandService.java
  src/main/java/umc/plantory/domain/wateringCan/repository/WateringCanRepository.java
Labels: :sparkles: FEAT

#82 [#81] 로그인 시 응답 DTO 에 유저 상태 추가
  src/main/java/umc/plantory/domain/kakao/converter/KakaoConverter.java
  src/main/java/umc/plantory/domain/member/dto/MemberResponseDTO.java
  src/main/java/umc/plantory/domain/token/service/MemberTokenCommandService.java
Labels: :recycle: REFACTOR

#85 [#78] 물 주기 이벤트 API 로직 수정
  src/main/java/umc/plantory/domain/terrarium/controller/TerrariumRestController.java
  src/main/java/umc/plantory/domain/terrarium/converter/TerrariumConverter.java
  src/main/java/umc/plantory/domain/terrarium/dto/TerrariumResponseDto.java
  src/main/java/umc/plantory/domain/terrarium/entity/Terrarium.java
  src/main/java/umc/plantory/domain/terrarium/service/TerrariumCommandService.java
  src/main/java/umc/plantory/domain/wateringCan/repository/WateringCanRepository.java
  src/main/java/umc/plantory/domain/wateringCan/repository/WateringCanRepositoryCustom.java
  src/main/java/umc/plantory/domain/wateringCan/repository/WateringCanRepositoryImpl.java
  src/main/java/umc/plantory/domain/wateringCan/repository/WateringEventRepository.java
  src/main/java/umc/plantory/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/plantory/global/apiPayload/exception/handler/WateringCanHandler.java
Labels: :recycle: REFACTOR

#96 [#88] 누적 감정 기록 횟수, 연속 기록 구현
  src/main/java/umc/plantory/domain/diary/repository/DiaryRepositoryCustom.java
  src/main/java/umc/plantory/domain/diary/repository/DiaryRepositoryImpl.java
  src/main/java/umc/plantory/domain/diary/service/DiaryCommandService.java
  src/main/java/umc/plantory/domain/member/entity/Member.java
  src/main/java/umc/plantory/domain/member/repository/MemberRepository.java
  src/main/java/umc/plantory/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/umc/plantory/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/umc/plantory/global/scheduler/Scheduler.java
  src/main/java/umc/plantory/global/scheduler/SchedulerJob.java
Labels: :sparkles: FEAT, :recycle: REFACTOR

#98 [#97] Flower Img 프론트에서 관리 -> flowerImgUrl 관련 코드 삭제
  src/main/java/umc/plantory/domain/flower/entity/Flower.java
  src/main/java/umc/plantory/domain/terrarium/converter/TerrariumConverter.java
  src/main/java/umc/plantory/domain/terrarium/dto/TerrariumResponseDto.java
  src/main/java/umc/plantory/domain/terrarium/service/TerrariumQueryService.java
Labels: :recycle: REFACTOR

#100 [#99] API URL 수정
  src/main/java/umc/plantory/domain/chat/controller/ChatRestController.java
  src/main/java/umc/plantory/domain/diary/controller/DiaryRestController.java
  src/main/java/umc/plantory/domain/member/controller/MemberRestController.java
  src/main/java/umc/plantory/domain/statistic/controller/StatisticRestController.java
  src/main/java/umc/plantory/domain/terrarium/controller/TerrariumRestController.java
  src/main/java/umc/plantory/domain/token/controller/MemberTokenRestController.java
Labels: :recycle: REFACTOR

#110 [#109] 트랜잭션으로 의도하지 않은 로직 수행하는 부분 수정 및 프론트 요청에 따라 응답에 닉네임 추가
  src/main/java/umc/plantory/domain/terrarium/converter/TerrariumConverter.java
  src/main/java/umc/plantory/domain/terrarium/dto/TerrariumResponseDto.java
  src/main/java/umc/plantory/domain/terrarium/service/TerrariumCommandService.java
Labels: :bug: BUG, :recycle: REFACTOR

#113 [#112] 테라리움 응답 수정 및 프로젝트 전체적인 Refactoring
  src/main/java/umc/plantory/domain/diary/dto/DiaryRequestDTO.java
  src/main/java/umc/plantory/domain/diary/service/DiaryQueryService.java
  src/main/java/umc/plantory/domain/flower/repository/FlowerRepository.java
  src/main/java/umc/plantory/domain/member/controller/MemberRestController.java
  src/main/java/umc/plantory/domain/member/converter/MemberConverter.java
  src/main/java/umc/plantory/domain/member/dto/MemberDataDTO.java
  src/main/java/umc/plantory/domain/member/service/MemberQueryService.java
  src/main/java/umc/plantory/domain/statistic/controller/StatisticRestController.java
  src/main/java/umc/plantory/domain/statistic/converter/StatisticConverter.java
  src/main/java/umc/plantory/domain/statistic/dto/StatisticResponseDTO.java
  src/main/java/umc/plantory/domain/statistic/service/StatisticQueryService.java
  src/main/java/umc/plantory/domain/statistic/service/StatisticQueryUseCase.java
  src/main/java/umc/plantory/domain/terrarium/controller/TerrariumRestController.java
  src/main/java/umc/plantory/domain/terrarium/converter/TerrariumConverter.java
  src/main/java/umc/plantory/domain/terrarium/dto/TerrariumResponseDto.java
  src/main/java/umc/plantory/domain/terrarium/entity/Terrarium.java
  src/main/java/umc/plantory/domain/terrarium/repository/TerrariumRepository.java
  src/main/java/umc/plantory/domain/terrarium/service/TerrariumQueryService.java
  src/main/java/umc/plantory/domain/terrarium/service/TerrariumQueryUseCase.java
  src/main/java/umc/plantory/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/plantory/global/config/SwaggerConfig.java
Labels: :recycle: REFACTOR

#119 [#118] 테라리움 응답 포맷 변경 및 필드 추가
  src/main/java/umc/plantory/domain/terrarium/converter/TerrariumConverter.java
  src/main/java/umc/plantory/domain/terrarium/dto/TerrariumResponseDto.java
Labels: :recycle: REFACTOR

#121 [#120] 내용 없이 일기 임시 저장 시, 임시 제목 부여
  src/main/java/umc/plantory/domain/diary/service/DiaryCommandService.java
Labels: :bug: BUG

#111 [#105] 최근 7일 평균 수면 시간 조회 구현
  src/main/java/umc/plantory/domain/diary/dto/DiaryProjectionDTO.java
  src/main/java/umc/plantory/domain/diary/repository/DiaryRepository.java
  src/main/java/umc/plantory/domain/diary/repository/DiaryRepositoryCustom.java
  src/main/java/umc/plantory/domain/diary/service/DiaryCommandService.java
  src/main/java/umc/plantory/domain/member/entity/Member.java
  src/main/java/umc/plantory/domain/member/repository/MemberRepository.java
  src/main/java/umc/plantory/global/scheduler/Scheduler.java
  src/main/java/umc/plantory/global/scheduler/SchedulerJob.java
Labels: :sparkles: FEAT

#108 [#76] 챗봇 대화 이력 조회 API 통합
  src/main/java/umc/plantory/domain/chat/controller/ChatRestController.java
  src/main/java/umc/plantory/domain/chat/converter/ChatConverter.java
  src/main/java/umc/plantory/domain/chat/dto/ChatResponseDTO.java
  src/main/java/umc/plantory/domain/chat/repository/ChatRepository.java
  src/main/java/umc/plantory/domain/chat/repository/ChatRepositoryCustom.java
  src/main/java/umc/plantory/domain/chat/repository/ChatRepositoryImpl.java
  src/main/java/umc/plantory/domain/chat/service/ChatCommandService.java
  src/main/java/umc/plantory/domain/chat/service/ChatCommandUseCase.java
  src/main/java/umc/plantory/domain/chat/service/ChatQueryService.java
  src/main/java/umc/plantory/domain/chat/service/ChatQueryUseCase.java
  src/main/java/umc/plantory/domain/terrarium/controller/TerrariumRestController.java
  src/main/java/umc/plantory/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/plantory/global/apiPayload/exception/handler/PaginationHandler.java
Labels: :recycle: REFACTOR

#123 [#122] 테라리움 상세 조회 응답 포맷 수정
  src/main/java/umc/plantory/domain/member/controller/MemberRestController.java
  src/main/java/umc/plantory/domain/terrarium/converter/TerrariumConverter.java
  src/main/java/umc/plantory/domain/terrarium/dto/TerrariumResponseDto.java
  src/main/java/umc/plantory/domain/terrarium/service/TerrariumQueryService.java
Labels: :recycle: REFACTOR

#125 [#124] @Min 어노테이션 삭제, 내부 로직으로 처리
  src/main/java/umc/plantory/domain/chat/controller/ChatRestController.java
  src/main/java/umc/plantory/domain/chat/service/ChatQueryService.java
Labels: :rotating_light: HOTFIX

#133 [#132] 프론트 요청에 맞게 테라리움 월별 조회 응답 포맷 변경
  src/main/java/umc/plantory/domain/terrarium/controller/TerrariumRestController.java
  src/main/java/umc/plantory/domain/terrarium/converter/TerrariumConverter.java
  src/main/java/umc/plantory/domain/terrarium/dto/TerrariumResponseDto.java
  src/main/java/umc/plantory/domain/terrarium/service/TerrariumQueryService.java
  src/main/java/umc/plantory/domain/terrarium/service/TerrariumQueryUseCase.java
Labels: :recycle: REFACTOR

#134 [#131] 데모데이 시연용 더미 데이터 입력 자동화
  src/main/java/umc/plantory/domain/diary/repository/DiaryRepository.java
  src/main/java/umc/plantory/domain/member/entity/Member.java
  src/main/java/umc/plantory/domain/member/event/MemberEvent.java
  src/main/java/umc/plantory/domain/member/event/OnboardingListener.java
  src/main/java/umc/plantory/domain/member/event/OnboardingService.java
  src/main/java/umc/plantory/domain/member/service/MemberCommandService.java
  src/main/java/umc/plantory/global/config/AsyncConfig.java
Labels: :recycle: REFACTOR

#138 [#137] 데모데이 모니터링용 로그 추가
  src/main/java/umc/plantory/domain/chat/service/ChatCommandService.java
  src/main/java/umc/plantory/domain/chat/service/ChatQueryService.java
  src/main/java/umc/plantory/domain/diary/service/DiaryCommandService.java
  src/main/java/umc/plantory/domain/diary/service/DiaryQueryService.java
  src/main/java/umc/plantory/domain/image/controller/ImageRestController.java
  src/main/java/umc/plantory/domain/image/service/ImageService.java
  src/main/java/umc/plantory/domain/image/service/ImageUseCase.java
  src/main/java/umc/plantory/domain/member/controller/MemberRestController.java
  src/main/java/umc/plantory/domain/member/service/MemberCommandService.java
  src/main/java/umc/plantory/domain/member/service/MemberQueryService.java
  src/main/java/umc/plantory/domain/statistic/service/StatisticQueryService.java
  src/main/java/umc/plantory/domain/terrarium/controller/TerrariumRestController.java
  src/main/java/umc/plantory/domain/terrarium/service/TerrariumCommandService.java
  src/main/java/umc/plantory/domain/terrarium/service/TerrariumQueryService.java
  src/main/java/umc/plantory/domain/terrarium/service/TerrariumQueryUseCase.java
  src/main/java/umc/plantory/domain/token/service/MemberTokenCommandService.java
Labels: :recycle: REFACTOR
